Add Automatic Cleaning Mode and Logging Features to Samsung AC Integration
lanwin/esphome_samsung_ac pull request #160
Opened 2024-08-14 14:29 UTC by omerfaruk-aran

This pull request introduces the automatic cleaning mode to the Samsung AC integration, enhancing the functionality and ensuring a more hygienic environment.

- Resolves #121

**Key Features:**

**- Automatic Cleaning Mode:**
 - Ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed, providing an added layer of cleanliness and efficiency.

**- Logging Enhancements:**
 - **debug_log_messages:** This option allows for logging of all defined messages. When enabled (true), all standard log messages will be recorded, providing a clear overview of system operations.
 - **debug_log_undefined_messages:** This option logs any undefined messages, helping in debugging and identifying any unexpected or unhandled operations.
 - If both debug_log_messages and debug_log_undefined_messages are set to false, only the logs for the operations executed via SmartThings will be visible. This approach minimizes unnecessary log clutter while still providing essential logging for new features and functions.

**Changes Made Based on Previous Feedback:**
- Resolved all conflicts.
- Fixed indentation issues for better code readability.
- Renamed log parameters to start with debug_ for consistency with existing log options.
- Implemented the debug_log_messages functionality that was previously missing.
- Corrected the repository source address in the example YAML file.

This PR addresses and resolves the issues raised in the previous pull request and is now ready for review.

2024-08-16 10:10 UTC, lanwin requested changes
Thank you for that pullrequest!

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol.cpp
> +		bool debug_log_messages = false;
The indentation need to be fixed here.

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol.cpp
> +        //bool debug_log_packets = false;
This can be getting removed.

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol.h
> +        //extern bool debug_log_packets;
You could please also remove that.

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol_nasa.cpp
> +                std::string payload = std::to_string(message.value);
From code reading perspective this is a good change. But consider that we are targeting a device with a pretty slow processor.

Your change means that:
1. topic_prefix needs to be added to the string (before it was a const string.
2. topic_suffix get always converted even in the default case.
3. payload gets always converted to string even in the default case.

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol_nasa.h
> +            VAR_IN_TEMP_EVA_OUT_F = 0x4206,
can you please sync the casing with the other value?

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol_non_nasa.cpp
> +            if (debug_log_messages)
This did not do what you would like to archive. This also print the undefined messages.

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol_nasa.cpp
> +            if (debug_log_messages)
This did not do what you would like to archive. This also print the undefined messages.

2024-08-16 10:10 UTC, lanwin commented on components/samsung_ac/protocol_nasa.cpp
> +                if (debug_log_messages)
Adding the debug_log_message if to each case makes this already too large method even more larger. Can you please add and LOG_MESSAGE marco for that case?

2024-08-16 19:07 UTC, omerfaruk-aran commented
Requested changes have been implemented, please review the updates.

2024-08-22 12:19 UTC, merged

2024-08-22 12:19 UTC, lanwin commented
Thank you!

2024-08-22 16:14 UTC, hnykda commented
Wow, thanks @omerfaruk-aran . May I know how you actually figured this out? Could we use something similar for the #144 sound?

2024-08-22 16:44 UTC, lanwin commented
@hnykda only when we found the corresponding messages...but for now we have no hint.