Improve configuration files and README.md
lanwin/esphome_samsung_ac pull request #38
Opened 2023-12-05 21:05 UTC by bzumik1

Make special configuration for Plug&Play version so it is even easier for new joiners.

2023-12-11 11:42 UTC, lanwin requested changes
Ok after rethinking this it was a bad idea to split the examples. Could you please join them back. 

Also the logger stuff should be copied over from the DIY example. Since this is a mayor problem when you use a NodeMCU or a D1 Mini.

2023-12-11 11:42 UTC, lanwin commented on config-plug-and-play.yaml
> +    name: "${name} uptime"
I think this should not be are. This are custom stuff not everyone needs.

2023-12-11 11:42 UTC, lanwin commented on config-plug-and-play.yaml
> +        name: "AC Unit 2 - mode"
To make it more clear we should remove the comments here and add just the basic climate control and the comment to change the address.

2023-12-11 11:42 UTC, lanwin commented on config-plug-and-play.yaml
> +        name: "AC Unit 1"
I would suggest to use a room name instead of "AC Unit 1". I would guess most people use room names here.

2023-12-11 13:37 UTC, bzumik1 commented
Will do

2024-01-18 08:11 UTC, lanwin commented
Thak you @bzumik1 I have decided to discard the DIY stuff and updated the readme based on your seggstions. So this can be closed.

2024-01-18 08:11 UTC, closed without merging